<!-- LTeX: language=en-US -->

# Organization of the Course {.unnumbered}

### Timetable {.unnumbered}

```{r, echo=FALSE}
suppressPackageStartupMessages(library("kableExtra"))
suppressPackageStartupMessages(library("tidyverse"))

timetable <- tibble("Day"          = c("Monday",         "Wednesday"),
                    "Time"         = c("16:15-18:00",    "08:45-10:00"),
                    "Lecture Hall" = c("Lecture Hall F", "Lecture Hall N"))
           
timetable %>% kbl() %>%  kable_styling()
```

### Syllabus {.unnumbered}

-   Maximum Likelihood Estimation
-   Bootstrap
-   Nonparametric Regression <!-- * Functional Data Analysis -->

# 

# Organization of the Course {.unnumbered}

The lecture takes place on Mondays and Wednesdays (16:15-17:45) in lecture hall F.

### Lecture Material {.unnumbered}

-   The lecture material is on ecampus (pwd: compustat).

::: callout-note
## Note

This script will be updated regularly during the semester. Typos and errors will be corrected, and new sections, exercises, and solutions may be added over time. Please make sure that you always use the most recent version uploaded on ecampus.
:::

-   Recommend Books:

    -   Elements of Statistical Learning: Data Mining, Inference and Prediction (by by Jerome H. Friedman, Robert Tibshirani, and Trevor Hastie). Freely available [**pdf version**](https://web.stanford.edu/~hastie/ElemStatLearn/)
    -   All of Statistics: A Concise Course in Statistical Inference (by Larry A. Wasserman)
    -   All of Nonparametric Statistics (by Larry A. Wasserman)

### Miscellaneous {.unnumbered}

-   [**Grace Wahba**](https://en.wikipedia.org/wiki/Grace_Wahba), "the mother of smoothing splines," won the [International Prize (aka the Nobel Prize) in Statistics](https://www.statprize.org/2025-International-Prize-in-Statistics-Awarded-to-Grace-Wahba.cfm). Some of her well known contributions are:
    -   The [representer theorem](https://www.sciencedirect.com/science/article/pii/0022247X71901843); see also the [YouTube-Video](https://www.youtube.com/watch?v=8Ae_QzwwR_U) by [Very Normal](https://www.youtube.com/@very-normal)
    -   Generalized Cross-Validation

### Information on the Exam {.unnumbered}

-   You are allowed to use a handwritten cheat-sheet (**one side** of a DIN A4 page).
-   You are allowed to use a non-programmable scientific calculator.
-   Please, do **not** use a pencil.
-   Exam dates and times are published by the [examinations office](https://www.econ.uni-bonn.de/examinations/en/dates/dates?set_language=en).
